### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shapetrix** [arkms/Unity---Simple-Facebook-and-Twitter#1]
I'm not sure why but when I go to post to face book it pops up to where you can add a comment and post and it looks one way but then after you post it switches information. I attached a screen shot for both. I didn't change very much code in the fb manager only the test script. Not sure where i'm going wrong. 
![screen shot 2016-08-03 at 9 29 12 pm](https://cloud.githubusercontent.com/assets/14881423/17388675/49710180-59c3-11e6-9084-41c8db48d38b.png)
![screen shot 2016-08-03 at 9 30 00 pm](https://cloud.githubusercontent.com/assets/14881423/17388676/497407fe-59c3-11e6-928b-fe981e11ad53.png)

**Comment by arkms** [comment]
In 2015 Facebook do a little changes if you share link to google play or itunes store, facebook profile or page, they ignore image and descriptions that you specify in the share with the parameters.
This came in [Feed Dialog Documentation ](https://developers.facebook.com/docs/sharing/reference/feed-dialog)

> Note: If your app share links to the iTunes or Google Play stores, or to a Facebook profile or page, we do not post any images or descriptions that you specify in the share with the parameters below. Instead we post some app information we scrape from the app store or Facebook page directly with the Webcrawler. This may not include images

Maybe this is your problem.
You ¿Are you trying to share from a Ios / Android device?

**Comment by Shapetrix** [comment]
currently I am trying to share from my mac book pro but ultimately I am trying to get it set up for sharing from ios and Android. I attached a screen shot of what I have for the test code. 
![screen shot 2016-08-04 at 10 20 40 pm](https://cloud.githubusercontent.com/assets/14881423/17425340/cf97d512-5a91-11e6-952a-5b12a980e0f4.png)

**Comment by arkms** [comment]
Its look everything fine in SocialManager.

Can you paste the final url that open in your browser for post on Facebook. (The URL from the first screenshot)

**Comment by Shapetrix** [comment]
yeah this is the facebook manager script 
![screen shot 2016-08-05 at 12 18 05 am](https://cloud.githubusercontent.com/assets/14881423/17426933/3776db78-5aa2-11e6-8541-c7223a5db234.png)

**Comment by arkms** [comment]
Ok, the problem is your link "https://itunes.apple.com/us/app/id633231270" is of a itunes store, so Facebook ignore your custom description, this is was new in middle of 2015.
![capture1](https://cloud.githubusercontent.com/assets/1153475/17428066/15cb1da0-5aab-11e6-8fba-212441c2aa1d.JPG)

Now, a tip is use a web page with link to your game. This can redirect you automatic to the store or can be  a nice web page with buttons to the store, like this: [Viva Sancho Villa](http://vivasanchovilla.com/)
![capture2](https://cloud.githubusercontent.com/assets/1153475/17428100/65dc70fa-5aab-11e6-8a6f-3deac0e4870c.JPG)

Now with your image, where is hosted? The image can not be hosted in Facebook. Facebook is a little anoying with this :/

Other alternative for Android and iOS is use their native share :
[Link1](https://github.com/ChrisMaire/unity-native-sharing)
[Link2](https://github.com/frispgames/frisp-social-unity-asset)

**Comment by Shapetrix** [comment]
sweet got it working thanks for your help

**Comment by arkms** [comment]
Nice! :)   Your welcome.

**Comment by Shapetrix** [comment]
sorry to be a pain (still new to coding). I had it working but then when I tried to do an iOS build it popped this error Assets/Plugins/TwitterManager.cs(50,17): error CS0103: The name `SocialPost' does not exist in the current context so it's complaining about the if else check for android or iOS. I am trying to use Game Center so I'm not sure if that script is interfering or not. Thanks again for all your help.

**Comment by arkms** [comment]
hehe, no problem :)
In top of TwitterManager.cs and FacebookManager.cs there is this line of code"//#define WEBONLY"
uncomment and try again.

If you have another error, check if you have one of this scripts ande delete it:
[Plugins](https://github.com/arkms/Unity---Simple-Facebook-and-Twitter/tree/master/Assets/Plugins)

-SocialPost.cs
-iOS/SocialPost.mm
-iOS/SocialPostClass.h

**Comment by Shapetrix** [comment]
So I uncommented those couple lines like you said and checked for the other scripts but I'm getting the same error as I had before . I attached a screen shot of my code. 
![screen shot 2016-08-08 at 11 07 13 pm](https://cloud.githubusercontent.com/assets/14881423/17504331/a5bae4e4-5dbd-11e6-92f3-2259eca4bffd.png)

**Comment by Shapetrix** [comment]
figured it out :) thanks

**Comment by arkms** [comment]
Good :)
